pipeline:
  name: AFTCodeScanning-HarnessCI
  identifier: AFTCodeScanningHarnessCI
  projectIdentifier: AWSIAC
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GITPrivateKiran99aws
        repoName: harness-demo-pipeline
        build: <+input>
  stages:
    - stage:
        name: GitClone-1
        identifier: GitClone1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: GitClone
                      name: GitClone_1
                      identifier: GitClone_1
                      spec:
                        connectorRef: GitPublickiran99aws
                        repoName: terraform-aws-control_tower_account_factory
                        cloneDirectory: /harness/terraform-aws-control_tower_account_factory
                        build:
                          type: branch
                          spec:
                            branch: main
                  - step:
                      type: GitClone
                      name: GitClone_2
                      identifier: GitClone_2
                      spec:
                        connectorRef: GITPrivateKiran99aws
                        repoName: harness-demo-pipeline
                        cloneDirectory: /harness/harness-demo-pipeline
                        build:
                          type: branch
                          spec:
                            branch: Develop
