pipeline:
  name: AFTCodeScanning-HarnessCI
  identifier: AFTCodeScanningHarnessCI
  projectIdentifier: AWSIAC
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GITPrivateKiran99aws
        repoName: harness-demo-pipeline
        build: <+input>
  stages:
    - stage:
        name: GitClone-1
        identifier: GitClone1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: GitClone
                      name: CloneAWSRepo
                      identifier: GitClone_1
                      spec:
                        connectorRef: GitPublickiran99aws
                        repoName: terraform-aws-control_tower_account_factory
                        cloneDirectory: /harness/terraform-aws-control_tower_account_factory
                        build:
                          type: branch
                          spec:
                            branch: main
                  - step:
                      type: GitClone
                      name: CloneTargetRepo
                      identifier: GitClone_2
                      spec:
                        connectorRef: GITPrivateKiran99aws
                        repoName: harness-target-repo
                        cloneDirectory: /harness/harness-target-repo
                        build:
                          type: branch
                          spec:
                            branch: Develop
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      git config --global user.email "kiran99aws@gmail.com"
                      git config --global user.name "Kiran Nare"
                      git config pull.rebase true
                      cd /harness/harness-target-repo
                      git pull  https://github.com/aws-ia/terraform-aws-control_tower_account_factory.git main:awsia-main --allow-unrelated-histories
                      git checkout -b awsia-main
                      touch test
                      git status
                      git commit -m "Push AWS Public Code to awsia-main branch"
                      echo "text secret is: " <+secrets.getValue("kiran99aws-pat")>
                      git remote set-url origin  "https://kiran99aws:<+secrets.getValue("kiran99aws-pat")>@github.com/kiran99aws/harness-target-repo"
                      git push --set-upstream origin awsia-main
        variables:
          - name: gh_pat
            type: String
            description: ""
            required: false
            value: Test_Value
