pipeline:
  name: AFTCodeScanning-HarnessCI
  identifier: AFTCodeScanningHarnessCI
  projectIdentifier: AWSIAC
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GITPrivateKiran99aws
        repoName: harness-demo-pipeline
        build: <+input>
  stages:
    - stage:
        name: GitClone-1
        identifier: GitClone1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: GitClone
                      name: GitClone_1
                      identifier: GitClone_1
                      spec:
                        connectorRef: GitPublickiran99aws
                        repoName: terraform-aws-control_tower_account_factory
                        cloneDirectory: /harness/terraform-aws-control_tower_account_factory
                        build:
                          type: branch
                          spec:
                            branch: main
                  - step:
                      type: GitClone
                      name: GitClone_2
                      identifier: GitClone_2
                      spec:
                        connectorRef: GITPrivateKiran99aws
                        repoName: harness-demo-pipeline
                        cloneDirectory: /harness/harness-demo-pipeline
                        build:
                          type: branch
                          spec:
                            branch: Develop
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      git config --global user.email "kiran99aws@gmail.com"
                      git config --global user.name "Kiran Nare"
                      cd /harness/harness-demo-pipeline
                      git checkout -b public-master
                      touch test
                      git status
                      git add .
                      git commit -m "Push AWS Public Code to new branch"
                      echo "text secret is: " <+secrets.getValue("kiran99aws-pat")>
                      git config --global credential.helper '!f() { sleep 1; echo "username=git token=<+secrets.getValue("kiran99aws-pat")>"; }; f'
                      git push --set-upstream origin public-master
        variables:
          - name: gh_pat
            type: String
            description: ""
            required: false
            value: Test_Value
