pipeline:
  identifier: Build_kiran99aws_harness_demo_pipeline_1713905698963
  name: Build harness-demo-pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: kiran99aws/harness-demo-pipeline
  stages:
    - stage:
        name: Clone Codebase
        identifier: Clone_Codebase
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: GitClone
                      name: GitClone_1
                      identifier: GitClone_1
                      spec:
                        connectorRef: account.Github
                        repoName: kiran99aws/harness-template-repo
                        cloneDirectory: /harness/harness-template-repo
                        build:
                          type: branch
                          spec:
                            branch: main
                  - step:
                      type: GitClone
                      name: GitClone_2
                      identifier: GitClone_2
                      spec:
                        connectorRef: account.Github
                        repoName: kiran99aws/harness-target-repo
                        cloneDirectory: /harness/harness-target-repo
                        build:
                          type: branch
                          spec:
                            branch: main
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      git config --global user.email "kiran99aws@gmail.com"
                      git config --global user.name "Kiran Nare"
                      cd /harness/harness-target-repo 
                      cp -prf /harness/harness-template-repo .
                      git status
                      git add .
                      git commit -m "Copying Code from Template Repo"
                      git push
                      echo "All Complete"
