pipeline:
  identifier: Build_kiran99aws_harness_demo_pipeline_1713905698963
  name: Build harness-demo-pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: kiran99aws/harness-template-repo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: gitpush
                  name: git-push
                  description: This step copies code to target repository
                  type: Run
                  spec:
                    image: appleboy/drone-git-push
                    settings:
                      branch: master
                      repoName: kiran99aws/harness-demo-pipeline
                      force: false
                      commit: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
