pipeline:
  identifier: Build_kiran99aws_harness_demo_pipeline_1713905698963
  name: Build harness-demo-pipeline
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: kiran99aws/harness-demo-pipeline
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: Scan-Code
        identifier: ScanCode
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
          execution:
            steps:
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: critical
